export enum TipoRitenuta {
  RITENUTA_PERSONE_FISICHE = 'RT01',
  RITENUTA_PERSONE_GIURIDICHE = 'RT02',
  CONTRIBUTO_INPS = 'RT03',
  CONTRIBUTO_ENASARCO = 'RT04',
  CONTRIBUTO_ENPAM = 'RT05',
  ALTRO_CONTRIBUTO_PREVIDENZIALE = 'RT06',
}
